apiVersion: batch/v1
kind: Job
metadata:
  name: dbmigration
spec:
  template:
    spec:
      containers:
      - name: dbmigration
        image: localhost:5000/dbmigration:latest
        env:
            - name: POSTGRES_CONNECTION_STRING
              value: "Host=postgres-service;Database=postgres;Username=postgres;Password=CHANGEME"
      restartPolicy: Never
  backoffLimit: 4